import type { StorybookConfig } from '@storybook/nextjs'
import { VanillaExtractPlugin } from '@vanilla-extract/webpack-plugin'
import path from 'path'

const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-onboarding',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/nextjs',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
  webpackFinal(config) {
    // Add Vanilla-Extract
    config.plugins?.push(new VanillaExtractPlugin())

    // 별칭 설정 추가
    config.resolve = config.resolve || {}
    config.resolve.alias = {
      ...config.resolve.alias,
      '@/system': path.resolve(__dirname, '../src/system'),
    }

    // // Exclude vanilla extract files from regular css processing
    // config.module?.rules?.forEach((rule) => {
    //   if (
    //     typeof rule !== 'string' &&
    //     rule &&
    //     rule.test instanceof RegExp &&
    //     rule.test.test('test.css')
    //   ) {
    //     rule.exclude = /\.vanilla\.css$/i
    //   }
    // })

    // config.module?.rules?.push({
    //   test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
    //   // use: [
    //   //   MiniCssExtractPlugin.loader,
    //   //   {
    //   //     loader: require.resolve("css-loader"),
    //   //     options: {
    //   //       url: false, // Required as image imports should be handled via JS/TS import statements
    //   //     },
    //   //   },
    //   // ],
    // })

    return config
  },
}
export default config
